# PYTORCH TENSORS - ADVANCED

In [3]:
%%html
<style type='text/css'>
.CodeMirror{
    font-size: 20px;
}

div.output_area pre {
    font-size: 20px;
}

div.text_cell_render {
    font-size: 20px;
}
</style>

In [2]:
%matplotlib inline

In [4]:
import torch
import warnings
warnings.filterwarnings('ignore')

## torch.tensor vs. torch.Tensor

In [5]:
i = torch.tensor(1)  # gives you a tensor with fixed value of 1
j = torch.Tensor(1)  # gives you a tensor of size 1 which is randomly initialized
i, j

(tensor(1), tensor([0.]))

## Tensor Size

In [6]:
import sys
a = 45   # int64
b = 45.2 # float64
print(type(a))
print(type(b))
print(sys.getsizeof(a)) # prints 28 bytes
print(sys.getsizeof(b)) # prints 24 bytes

# https://stackoverflow.com/questions/31469553/python-memory-consumption-in-64-bit-system-for-int-and-float
# 64 bit system
# int:   overhead = 20 bytes, value = 8 bytes
# float: overhead = 16 bytes, value = 8 bytes

<class 'int'>
<class 'float'>
28
24


In [7]:
import numpy as np
n_int = np.array([1, 2, 3])         # int64
n_float = np.array([1.0, 2.0, 3.0]) # float64
print(n_int.dtype)
print(n_float.dtype)

print(n_int.size)
print(n_float.size)

print(n_int.itemsize)
print(n_float.itemsize)

print(n_int.size * n_int.itemsize)
print(n_float.size * n_float.itemsize)

print(n_int.nbytes)
print(n_float.nbytes)

int64
float64
3
3
8
8
24
24
24
24


In [8]:
import torch
t_int = torch.tensor([1, 2, 3])                                 # int64
t_float_1 = torch.tensor([1.0, 2.0, 3.0])                       # flaot32 !!!!!!
t_float_2 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)  # flaot64 !!!!!!
print(t_int.dtype)
print(t_float_1.dtype)
print(t_float_2.dtype)

print(t_int.element_size())
print(t_float_1.element_size())
print(t_float_2.element_size())

print(t_int.nelement())
print(t_float_1.nelement())
print(t_float_2.nelement())

print(t_int.element_size() * t_int.nelement())
print(t_float_1.element_size() * t_float_1.nelement())
print(t_float_2.element_size() * t_float_2.nelement())

torch.int64
torch.float32
torch.float64
8
4
8
3
3
3
24
12
24


## Index & Slicing
![...](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FCockM%2Fbtr0il3N3WH%2FOHvaSRN5FJjGOccBKbdov0%2Fimg.png)
![...](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbMHRoV%2Fbtr0aPy62x9%2FNG959AvpryfGKTNiNY7Tck%2Fimg.png)

## view vs. transpose vs. reshape
- https://inmoonlight.github.io/2021/03/03/PyTorch-view-transpose-reshape/

In [9]:
t = torch.tensor([[[0, 1],
                   [2, 3],
                   [4, 5]],
                  [[6, 7],
                   [8, 9],
                   [10, 11]],
                  [[12, 13],
                   [14, 15],
                   [16, 17]],
                  [[18, 19],
                   [20, 21],
                   [22, 23]]])  # (4, 3, 2)
t.shape

torch.Size([4, 3, 2])

In [10]:
tv = t.view(4, 2, 3)
tv

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]])

In [11]:
tv.shape

torch.Size([4, 2, 3])

In [12]:
tv.is_contiguous()

True

In [13]:
t = torch.tensor([[[0, 1],
                   [2, 3],
                   [4, 5]],
                  [[6, 7],
                   [8, 9],
                   [10, 11]],
                  [[12, 13],
                   [14, 15],
                   [16, 17]],
                  [[18, 19],
                   [20, 21],
                   [22, 23]]])  # (4, 3, 2)
t.shape

torch.Size([4, 3, 2])

#### transpose
- tensor 에 저장된 데이터의 물리적 위치 순서와 상관없이 수학적 의미의 transpose를 수행한다.
- 따라서, 일반적으로 transpose가 수행된 tensor는 항상 contiguous 하지 않다.

In [14]:
tr = t.transpose(2, 1)
tr.shape

torch.Size([4, 2, 3])

In [15]:
tr

tensor([[[ 0,  2,  4],
         [ 1,  3,  5]],

        [[ 6,  8, 10],
         [ 7,  9, 11]],

        [[12, 14, 16],
         [13, 15, 17]],

        [[18, 20, 22],
         [19, 21, 23]]])

In [16]:
tr.is_contiguous()

False

#### view 는 contiguous 하지 않은 tensor에 대해서는 적용할 수 없다.

In [17]:
tr.view(4, 3, 2)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [18]:
tr2 = tr.contiguous()
tr2

tensor([[[ 0,  2,  4],
         [ 1,  3,  5]],

        [[ 6,  8, 10],
         [ 7,  9, 11]],

        [[12, 14, 16],
         [13, 15, 17]],

        [[18, 20, 22],
         [19, 21, 23]]])

In [19]:
tr3 = tr2.view(4, 3, 2)
tr3

tensor([[[ 0,  2],
         [ 4,  1],
         [ 3,  5]],

        [[ 6,  8],
         [10,  7],
         [ 9, 11]],

        [[12, 14],
         [16, 13],
         [15, 17]],

        [[18, 20],
         [22, 19],
         [21, 23]]])

#### tensor.reshape() == tensor.contiguous().view()
- reshape 은 강제로 tensor를 contiguous 하게 만들면서 shape을 변경

In [20]:
tr4 = tr.view(4, 3, 2)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [21]:
tr4 = tr.reshape(4, 3, 2)
tr4

tensor([[[ 0,  2],
         [ 4,  1],
         [ 3,  5]],

        [[ 6,  8],
         [10,  7],
         [ 9, 11]],

        [[12, 14],
         [16, 13],
         [15, 17]],

        [[18, 20],
         [22, 19],
         [21, 23]]])

## Memory: List vs. Tensor

![...](https://raw.githubusercontent.com/HiddenBeginner/hiddenbeginner.github.io/master/static/img/_posts/2020-1-21-pytorch_tensor/figure2.png)

In [22]:
a0 = 1.0
a1 = 2.0
a2 = 3.0

print(id(a0) , id(a1), id(a2))

5648616208 5650504944 5650513552


In [23]:
a = [a0, a1, a2]

print(id(a[0]) , id(a[1]), id(a[2]))
print(id(a))

5648616208 5650504944 5650513552
5653594944


In [24]:
import torch
b = torch.tensor([a0, a1, a2])

print(id(b[0]), id(b[1]), id(b[2]))
print(id(b))

5653591392 5653591392 5653591392
5653591232


## Efficient Memory Management

In [25]:
data = [[1.0, 2.0],
        [3.0, 4.0],
        [5.0, 6.0]]
a = torch.tensor(data)
print(a)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [26]:
b = a[1,:]
print(b)

tensor([3., 4.])


In [27]:
b[0] = -999
print(b)
print(a)

tensor([-999.,    4.])
tensor([[   1.,    2.],
        [-999.,    4.],
        [   5.,    6.]])


## Basic Tensor

In [28]:
a = [1.0, 2.0, 1.0]

In [29]:
a[0]

1.0

In [30]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [31]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [32]:
a[1]

tensor(1.)

In [33]:
float(a[1])

1.0

In [34]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [35]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [36]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [37]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [38]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [39]:
points.shape

torch.Size([3, 2])

In [40]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [41]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [42]:
points[0, 1]

tensor(1.)

In [43]:
points[0]

tensor([4., 1.])

## Storage, Offset, Stride
- https://hiddenbeginner.github.io/deeplearning/2020/01/21/pytorch_tensor.html
- 1차원 텐서이든, 2차원 텐서이든 혹은 d차원 텐서이든 모든 텐서는 메모리에 1차원 배열의 형태로 저장됨
- storage: 텐서를 효율적으로 다룰 수 있도록 만들어주는 이러한 1차원 배열 (인덱싱한 텐서의 값에 접근할 때 offset과 stride 사용)
![...](https://raw.githubusercontent.com/HiddenBeginner/hiddenbeginner.github.io/master/static/img/_posts/2020-1-21-pytorch_tensor/figure3.png)
  - 위 두 텐서에 대하여 storage의 offset은 모두 0
  - stride는 텐서 안의 어떤 한 값에서 다음 원소를 얻기 위하여 storage에서 뛰어 넘어야할 인덱스의 개수
    - storage의 stride는 텐서의 차원만큼 정의됨

In [44]:
a = torch.tensor([[3,1,8],
                  [0,9,2]])
print("============storage==========")
print(a.storage())
print("=============================")
print("Offset: ", a.storage_offset())
print("Strides: ", a.stride())

============storage==========
 3
 1
 8
 0
 9
 2
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
Offset:  0
Strides:  (3, 1)


In [45]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

### tenset[i, j] == storage[storage_offset + i * stirde[0] + j * stirde[1]]
### tenset[i, j, k] == storage[storage_offset + i * stirde[0] + j * stirde[1] + k * stirde[2]]

In [46]:
x1 = torch.arange(12).view((4, 3))
x1

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [47]:
x1.stride()

(3, 1)

In [48]:
x2 = x1.view(3, 4)
x2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [49]:
storage = x2.storage()
offset = x2.storage_offset()
stride = x2.stride()
offset, stride

(0, (4, 1))

In [50]:
item1 = x2[2, 1].item()
item1

9

In [51]:
item2 = storage[offset + 2 * x2.stride()[0] + 1 * x2.stride()[1]]
item2

9

In [52]:
x = torch.arange(1200).view((10, 30, 4))
storage = x.storage()
offset = x.storage_offset()
stride = x.stride()
offset, stride

(0, (120, 4, 1))

In [53]:
item1 = x[4, 23, 2].item()
item2 = storage[offset + 4 * stride[0] + 23 * stride[1] + 2 * stride[2]]
item1 == item2

True

![...](https://raw.githubusercontent.com/HiddenBeginner/hiddenbeginner.github.io/master/static/img/_posts/2020-1-21-pytorch_tensor/figure4.png)

In [54]:
a = torch.tensor([[3,1,1,2],
                  [8,0,3,4],
                  [9,2,5,6]])
print("============storage==========")
print(a.storage())
print("=============================")
print("Offset: ", a.storage_offset())
print("Strides: ", a.stride())

============storage==========
 3
 1
 1
 2
 8
 0
 3
 4
 9
 2
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 12]
Offset:  0
Strides:  (4, 1)


In [55]:
b = a[1:3, 1:3]
print("============storage==========")
print(b.storage())
print("=============================")
print("Offset: ", b.storage_offset())
print("Strides: ", b.stride())
storage = b.storage()
offset = b.storage_offset()
stride = b.stride()

============storage==========
 3
 1
 1
 2
 8
 0
 3
 4
 9
 2
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 12]
Offset:  5
Strides:  (4, 1)


In [56]:
id(a.storage()) == id(b.storage())

False

In [57]:
id(a.untyped_storage()) == id(b.untyped_storage())

True

In [58]:
b

tensor([[0, 3],
        [2, 5]])

In [59]:
item1 = b[1, 1].item()
item1

5

In [60]:
item2 = storage[offset + 1 * stride[0] + 1 * stride[1]]
item1 == item2

True

In [61]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0]

4.0

In [62]:
points.storage()[1]

1.0

In [63]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [64]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.stride()

(2, 1)

In [65]:
second_point = points[1]
second_point

tensor([5., 3.])

In [66]:
second_point.storage_offset()

2

In [67]:
second_point.size()

torch.Size([2])

In [68]:
second_point.shape

torch.Size([2])

In [69]:
second_point.stride()

(1,)

In [70]:
item1 = points[1, 1].item()
item1

3.0

In [71]:
item2 = second_point[1].item()
item2

3.0

In [72]:
item3 = points_storage[second_point.storage_offset() + 1 * second_point.stride()[0]]
item3

3.0

In [73]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [74]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [75]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [76]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [77]:
id(points.storage()) == id(points_t.storage())

True

In [78]:
id(points.untyped_storage()) == id(points_t.untyped_storage())

True

In [79]:
points.stride()

(2, 1)

In [80]:
points_t.stride()

(1, 2)

In [81]:
some_t = torch.ones(3, 4, 5)
some_t.shape

torch.Size([3, 4, 5])

In [82]:
transpose_t = some_t.transpose(0, 2)
transpose_t.shape

torch.Size([5, 4, 3])

In [83]:
some_t.stride()

(20, 5, 1)

In [84]:
transpose_t.stride()

(1, 5, 20)

In [85]:
points.is_contiguous()

True

In [86]:
points_t.is_contiguous()

False

In [87]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [88]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [89]:
points_t.stride()

(1, 2)

In [90]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [91]:
points_t_cont.stride()

(3, 1)

In [92]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [93]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [94]:
short_points.dtype

torch.int16

In [95]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [96]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [97]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [98]:
some_list = list(range(6))
some_list[:]     # <1>

[0, 1, 2, 3, 4, 5]

In [99]:
some_list[1:4]   # <2>

[1, 2, 3]

In [100]:
some_list[1:]    # <3>

[1, 2, 3, 4, 5]

In [101]:
some_list[:4]    # <4>

[0, 1, 2, 3]

In [102]:
some_list[:-1]   # <5>

[0, 1, 2, 3, 4]

In [103]:
some_list[1:4:2] # <6>

[1, 3]

In [104]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points[1:]       # <1>

tensor([[5., 3.],
        [2., 1.]])

In [105]:
points[1:, :]    # <2>

tensor([[5., 3.],
        [2., 1.]])

In [106]:
points[1:, 0]    # <3>

tensor([5., 2.])

In [107]:
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

## Working with NumPy

In [108]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [109]:
id(points) == id(points_np)

False

- points & points_np are objects of different Python types, so, as far as Python is concerned, they have different addresses
- However, they share an underlying C array in memory & modifying one in-place also modies the other

In [110]:
points.zero_()
points

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [111]:
print(points_np)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [112]:
points2 = torch.from_numpy(points_np)

In [113]:
points2.add_(10)
points2

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [114]:
points_np

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]], dtype=float32)

In [115]:
points

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

## torch save & load

In [116]:
torch.save(points, '../data/p1ch3/ourpoints.t')

In [117]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [118]:
points = torch.load('../data/p1ch3/ourpoints.t')
points

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [119]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [120]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

In [121]:
#  pip install h5py
import h5py

f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()
dset

<Closed HDF5 dataset>

In [122]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
dset

<HDF5 dataset "coords": shape (3, 4), type "<f4">

In [123]:
last_points = torch.from_numpy(dset[1:])
f.close()

In [124]:
last_points

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [125]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
points_gpu = points.to(device='cuda')

In [126]:
points_gpu = points.to(device='cuda:0')

AssertionError: Torch not compiled with CUDA enabled

In [127]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

AssertionError: Torch not compiled with CUDA enabled

In [128]:
points_gpu = points_gpu + 4

NameError: name 'points_gpu' is not defined

In [129]:
points_cpu = points_gpu.to(device='cpu')

NameError: name 'points_gpu' is not defined

In [130]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

AssertionError: Torch not compiled with CUDA enabled

In [131]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [132]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [133]:
a = torch.ones(3, 2)

In [134]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## torch.dot vs. torch.matmul vs. torch.mm vs. torch.bmm
- https://velog.io/@regista/torch.dot-torch.matmul-torch.mm-torch.bmm

In [135]:
batch1 = torch.randn(10, 3, 20, 10)
batch2 = torch.randn(10, 3, 10, 30)
res = torch.matmul(batch1, batch2)
res.size() # torch.Size([10, 3, 20, 30])

torch.Size([10, 3, 20, 30])

In [136]:
batch1 = torch.randn(10, 3, 20, 10)
batch2 = torch.randn(10, 3, 10, 30)
res = batch1 @ batch2
res.size() # torch.Size([10, 3, 20, 30])

torch.Size([10, 3, 20, 30])

In [137]:
batch1 = torch.randn(10, 20, 10)
batch2 = torch.randn(10, 10, 30)
res = torch.bmm(batch1, batch2)
res.size() # torch.Size([10, 3, 20, 30])

torch.Size([10, 20, 30])

- https://pytorch.org/docs/stable/generated/torch.bmm.html
- mat1 and mat2 must be 3-D tensors