In [5]:
import torch; print(torch.__version__)
import torch.nn as nn

2.0.0


In [6]:
# Define the neural network architecture
class SimpleRegressNN(nn.Module):
    def __init__(self, input_size):
        super(SimpleRegressNN, self).__init__()
        self.fc1 = nn.Linear(input_size, 3)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(3, 2)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(2, 1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.fc3(x)
        return x

In [7]:
# Set the parameters
input_size = 4  # Number of input features

# Create the neural network
model = SimpleRegressNN(input_size)

In [13]:
input = torch.randn(size=(4,))
output = model(input)

In [14]:
input

tensor([ 0.3528, -0.9256, -0.5813, -0.3039])

In [16]:
output

tensor([0.4514], grad_fn=<AddBackward0>)

In [17]:
target = torch.tensor([3.5])

In [18]:
target

tensor([3.5000])

- https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html#torch.nn.MSELoss

In [19]:
mse_loss = nn.MSELoss()

In [20]:
loss = mse_loss(output, target)

In [21]:
loss

tensor(9.2940, grad_fn=<MseLossBackward0>)