In [1]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, threshold=50)

In [3]:
import imageio.v2 as imageio

img_arr = imageio.imread('../data/p1ch4/image-dog/bobby.jpg')
type(img_arr), img_arr.shape, img_arr.dtype

(imageio.core.util.Array, (720, 1280, 3), dtype('uint8'))

In [18]:
img_arr

Array([[[238, 195, 137],
        [238, 195, 137],
        [238, 195, 137],
        ...,
        [214, 173, 125],
        [215, 175, 126],
        [215, 175, 126]],

       [[238, 195, 137],
        [238, 195, 137],
        [238, 195, 137],
        ...,
        [214, 173, 125],
        [215, 175, 126],
        [215, 175, 126]],

       [[238, 195, 137],
        [238, 195, 137],
        [238, 195, 137],
        ...,
        [214, 173, 125],
        [215, 175, 126],
        [215, 175, 126]],

       ...,

       [[214, 128,  79],
        [213, 127,  78],
        [212, 126,  77],
        ...,
        [187, 100,  64],
        [190, 103,  68],
        [193, 106,  72]],

       [[214, 128,  79],
        [213, 127,  78],
        [212, 126,  77],
        ...,
        [186,  99,  64],
        [190, 103,  69],
        [192, 105,  71]],

       [[214, 128,  79],
        [213, 127,  78],
        [212, 126,  77],
        ...,
        [186,  99,  65],
        [190, 103,  69],
        [192, 105,  72]]

In [6]:
img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)
out.shape

torch.Size([3, 720, 1280])

In [19]:
out

tensor([[[ 77,  77,  ..., 117, 116],
         [ 75,  76,  ..., 117, 116],
         ...,
         [215, 216,  ..., 174, 174],
         [215, 216,  ..., 158, 158]],

        [[ 45,  45,  ...,  77,  76],
         [ 43,  44,  ...,  77,  76],
         ...,
         [165, 166,  ..., 124, 124],
         [165, 166,  ..., 107, 107]],

        [[ 22,  22,  ...,  51,  50],
         [ 20,  21,  ...,  51,  50],
         ...,
         [ 78,  79,  ...,  55,  55],
         [ 78,  79,  ...,  41,  41]]], dtype=torch.uint8)

In [20]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

In [21]:
import os

data_dir = '../data/p1ch4/image-cats/'
filenames = [name for name in os.listdir(data_dir) if os.path.splitext(name)[-1] == '.png']

In [22]:
filenames

['cat1.png', 'cat2.png', 'cat3.png']

In [23]:
from PIL import Image
for i, filename in enumerate(filenames):
    image = Image.open(os.path.join(data_dir, filename))
    image.show()

In [24]:
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2, 0, 1)
    if len(img_t) > 3:
        img_t = img_t[:3] # <1>
    assert batch[i].shape == img_t.shape
    batch[i] = img_t

In [16]:
batch = batch.float()
batch /= 255.0
batch.dtype, batch.shape

(torch.float32, torch.Size([3, 3, 256, 256]))

In [17]:
batch

tensor([[[[0.6118, 0.5961,  ..., 0.5843, 0.6196],
          [0.6824, 0.5255,  ..., 0.5333, 0.5412],
          ...,
          [0.5059, 0.5098,  ..., 0.4745, 0.4471],
          [0.5059, 0.4824,  ..., 0.4745, 0.4706]],

         [[0.5451, 0.5294,  ..., 0.5294, 0.5765],
          [0.6275, 0.4667,  ..., 0.4784, 0.4863],
          ...,
          [0.4353, 0.4353,  ..., 0.4392, 0.4118],
          [0.4353, 0.4078,  ..., 0.4314, 0.4353]],

         [[0.5059, 0.4824,  ..., 0.5176, 0.5686],
          [0.6078, 0.4314,  ..., 0.4667, 0.4745],
          ...,
          [0.4235, 0.4235,  ..., 0.4588, 0.4314],
          [0.4196, 0.3843,  ..., 0.4510, 0.4549]]],


        [[[0.7922, 0.7569,  ..., 0.0510, 0.0471],
          [0.7804, 0.7529,  ..., 0.0549, 0.0549],
          ...,
          [0.2941, 0.2667,  ..., 0.1412, 0.1451],
          [0.3333, 0.4039,  ..., 0.1451, 0.1490]],

         [[0.5922, 0.5451,  ..., 0.0353, 0.0314],
          [0.5922, 0.5490,  ..., 0.0431, 0.0431],
          ...,
          [0.12

In [20]:
n_channels = batch.shape[1]

for c in range(n_channels):
    mean = torch.mean(batch[:, c])
    std = torch.std(batch[:, c])
    batch[:, c] = (batch[:, c] - mean) / std