In [2]:
import torch; print(torch.__version__)
import torch.nn as nn

2.0.0


In [3]:
# Define the neural network architecture
class SimpleNN(nn.Module):
    def __init__(self, input_size, output_size):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, 3)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(3, 2)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(2, output_size)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.fc3(x)
        return x

In [4]:
# Set the parameters
input_size = 4  # Number of input features
output_size = 3  # Number of output neurons (binary classification)

# Create the neural network
model = SimpleNN(input_size, output_size)

In [5]:
input = torch.randn(size=(4,))
output = model(input)

In [6]:
output

tensor([-0.4605,  0.1271,  0.2868], grad_fn=<AddBackward0>)

In [7]:
target = torch.tensor([0.0, 0.0, 1.0])

In [8]:
target

tensor([0., 0., 1.])

- https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#torch.nn.CrossEntropyLoss

In [9]:
cross_entropy_loss = nn.CrossEntropyLoss()

In [10]:
loss = cross_entropy_loss(output, target)

In [11]:
loss

tensor(0.8442, grad_fn=<DivBackward1>)

In [12]:
import torch.optim as optim
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [13]:
optimizer.zero_grad()
loss.backward()
optimizer.step()

In [14]:
output = model(input)

In [15]:
output

tensor([-0.4625,  0.1235,  0.2925], grad_fn=<AddBackward0>)

In [16]:
loss = cross_entropy_loss(output, target)

In [17]:
loss

tensor(0.8392, grad_fn=<DivBackward1>)