In [33]:
import torch; print(torch.__version__)
import torch.nn as nn

2.0.0


In [34]:
# Define the neural network architecture
class SimpleNN(nn.Module):
    def __init__(self, input_size, output_size):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, 3)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(3, 2)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(2, output_size)
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.fc3(x)
        x = self.softmax(x)
        return x

In [35]:
# Set the parameters
input_size = 4  # Number of input features
output_size = 3  # Number of output neurons (binary classification)

# Create the neural network
model = SimpleNN(input_size, output_size)

In [36]:
input = torch.randn(size=(4,))
output = model(input)

In [37]:
output

tensor([0.3349, 0.3946, 0.2705], grad_fn=<SoftmaxBackward0>)

In [38]:
target = torch.tensor([0.0, 0.0, 1.0])

In [39]:
target

tensor([0., 0., 1.])

- https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#torch.nn.CrossEntropyLoss

In [40]:
cross_entropy_loss = nn.CrossEntropyLoss()

In [41]:
loss = cross_entropy_loss(output, target)

In [42]:
loss

tensor(1.1627, grad_fn=<DivBackward1>)

In [43]:
import torch.optim as optim
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [44]:
optimizer.zero_grad()
loss.backward()
optimizer.step()

In [45]:
output = model(input)

In [46]:
output

tensor([0.3346, 0.3943, 0.2711], grad_fn=<SoftmaxBackward0>)

In [47]:
loss = cross_entropy_loss(output, target)

In [48]:
loss

tensor(1.1621, grad_fn=<DivBackward1>)